### ISSUE TITLE
Support coinmarketcap api

### ISSUE THREAD

**Issue by themotu** [polyrabbit/my-token#26]
Would be a nice addition

**Comment by polyrabbit** [comment]
Yes, `coinmarketcap` was supported - see https://github.com/polyrabbit/my-token/blob/master/exchange/coinmarketcap.go

But last year after being acquired by binance, they put a limit on free api quota. Users need to provide a `secret` to use those apis. I'm planning to implement this feature soon.

**Comment by polyrabbit** [comment]
Hi @themotu, I just released [v0.6.0](https://github.com/polyrabbit/my-token/releases/tag/v0.6.0) that supports coinmarketcap with an **api-key**.

You can specify it in the config file:
```yaml
exchanges:
- name: CoinMarketCap
  tokens:
  - BTC
  api_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

Or for an ad-hoc run, you can just set it in the command line:
```bash
mt CoinMarketCap.BTC.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
